"""
Prompt templates for IFT analysis.
"""

from .ift_prompts import (
    IFT_TECHNIQUES,
    TECHNIQUES_EXPLANATION,
    IFT_TECHNIQUES_LIST,
    INITIAL_GRAPH_PROMPT,
    MODULE_ANALYSIS_PROMPT,
    FINAL_DESIGN_SUMMARY_PROMPT,
    ASSET_IDENTIFICATION_PROMPT,
    VULNERABILITY_ANALYSIS_PROMPT
)

__all__ = [
    'IFT_TECHNIQUES',
    'TECHNIQUES_EXPLANATION',
    'IFT_TECHNIQUES_LIST',
    'INITIAL_GRAPH_PROMPT',
    'MODULE_ANALYSIS_PROMPT',
    'FINAL_DESIGN_SUMMARY_PROMPT',
    'ASSET_IDENTIFICATION_PROMPT',
    'VULNERABILITY_ANALYSIS_PROMPT'
]

